name: Build
on:
  push:
    branches:
      - source
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        token: ${{ secrets.PERSONAL_TOKEN }}
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        cd ./Maverick
        python -m pip install --upgrade pip
        pip install -r prod_req.txt
    - name: Build site
      run: |
        cd ./Maverick
        python ./build.py -c "../conf.py"
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        personal_token: ${{ secrets.PERSONAL_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./dist
        allow_empty_commit: false
